# Generated by Django 4.1.7 on 2023-04-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.cinema'),
        ),
    ]
