# Generated by Django 4.1.7 on 2023-04-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0003_rename_cinema_showtime_new_cinema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='new_cinema',
            new_name='cinema',
        ),
    ]
