# Generated by Django 4.1.7 on 2023-04-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '__first__'),
        ('cinemas', '0001_initial'),
        ('showtimes', '0004_rename_new_cinema_showtime_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='new_cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.cinema'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.cinema'),
        ),
    ]
