# Generated by Django 4.1.7 on 2023-04-05 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_cinema_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.city'),
        ),
    ]
