# Generated by Django 4.1.7 on 2023-04-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_cinema_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema_Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.cinema_chain'),
        ),
    ]
