# Generated by Django 4.1.7 on 2023-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_cinema_chain_cinema_cinema_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_chain',
            name='rating',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
