# Generated by Django 4.1.7 on 2023-04-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_cinema_chain_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cinema_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinemas', to='cinemas.cinema_chain'),
        ),
    ]
