# Generated by Django 4.1.7 on 2023-05-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_brand_remove_cinema_city_cinema_chain_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_chain',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_chains', to='cinemas.brand'),
        ),
    ]
