# Generated by Django 4.1.7 on 2023-05-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_cinema_chain_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='address',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
