# Generated by Django 4.1.7 on 2023-04-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('trailer_link', models.CharField(max_length=5000)),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField()),
                ('duration_minute', models.IntegerField()),
                ('age_limit', models.IntegerField()),
            ],
        ),
    ]
