# Generated by Django 4.1.7 on 2023-04-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('trailer_link', models.URLField()),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField()),
                ('duration_minute', models.PositiveIntegerField()),
                ('age_limit', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, default='', upload_to='movie_covers/')),
                ('banner_image', models.ImageField(blank=True, default='', upload_to='movie_banners/')),
                ('casts', models.ManyToManyField(related_name='casts', to='casts.cast')),
                ('director', models.ManyToManyField(related_name='directors', to='casts.cast')),
            ],
        ),
    ]
