# Generated by Django 4.1.7 on 2023-04-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(blank=True, null=True, related_name='casts', to='casts.cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, related_name='directors', to='casts.cast'),
        ),
    ]
