# Generated by Django 4.1.7 on 2023-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_casts_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_id',
            field=models.CharField(default='cEMEjXx848c', max_length=255),
            preserve_default=False,
        ),
    ]
