# Generated by Django 4.1.7 on 2023-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_trailer_link_movie_trailer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.TextField(),
        ),
    ]
