# Generated by Django 4.1.7 on 2023-04-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('movies', '0004_alter_movie_banner_image_alter_movie_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.tag'),
        ),
    ]
