# Generated by Django 4.1.7 on 2023-04-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0001_initial'),
        ('tags', '0001_initial'),
        ('movies', '0005_rename_director_movie_directors_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(blank=True, related_name='casts', to='casts.cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directors', to='casts.cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
