# Generated by Django 4.1.7 on 2023-06-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sale_time',
            new_name='sale_time',
        ),
    ]
