# Generated by Django 4.1.7 on 2023-04-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=100000, max_length=50),
            preserve_default=False,
        ),
    ]
