# Generated by Django 4.1.7 on 2023-06-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_sale_time_payment_sale_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
