# Generated by Django 4.1.7 on 2023-05-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_code',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_row',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
