# Generated by Django 4.1.7 on 2023-06-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_sale_date_payment_sale_time_ticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.payment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
