# Generated by Django 4.1.7 on 2023-06-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
