# Generated by Django 4.1.7 on 2023-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_path', models.TextField()),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
