# Generated by Django 4.1.7 on 2023-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='image_path',
            field=models.TextField(default='https://www.themoviedb.org/t/p/w300_and_h450_bestv2/83o3koL82jt30EJ0rz4Bnzrt2dd.jpg'),
            preserve_default=False,
        ),
    ]
